--REGIONES
insert into REGION values(12,'METROPOLITANA');
insert into REGION values(24,'ANTOFAGASTA');
insert into REGION values(36,'NUBLE');
insert into REGION values(48,'VALPARAISO');
insert into REGION values(60,'BIO-BIO');
insert into REGION values(72,'O.HIGGINS');
--COMUNA

    --nuble
    insert into COMUNA values(seq_comunaID.nextval,'Bulnes',36);
    insert into COMUNA values(seq_comunaID.nextval,'Chillan',36);
    insert into COMUNA values(seq_comunaID.nextval,'Chillan Viejo',36);
    insert into COMUNA values(seq_comunaID.nextval,'El Carmen',36);
    insert into COMUNA values(seq_comunaID.nextval,'Pemuco',36);
    insert into COMUNA values(seq_comunaID.nextval,'Pinto',36);
    insert into COMUNA values(seq_comunaID.nextval,'Quillon',36);
    insert into COMUNA values(seq_comunaID.nextval,'San Ignacion',36);
    insert into COMUNA values(seq_comunaID.nextval,'Yungay',36);
    insert into COMUNA values(seq_comunaID.nextval,'Quirihue',36);
    insert into COMUNA values(seq_comunaID.nextval,'Cobquecura',36);
    insert into COMUNA values(seq_comunaID.nextval,'Coelemu',36);
    insert into COMUNA values(seq_comunaID.nextval,'Ninhue',36);
    insert into COMUNA values(seq_comunaID.nextval,'Portezuelo',36);
    insert into COMUNA values(seq_comunaID.nextval,'Renquil',36);
    insert into COMUNA values(seq_comunaID.nextval,'Trehuaco',36);
    insert into COMUNA values(seq_comunaID.nextval,'San Carlos',36);
    insert into COMUNA values(seq_comunaID.nextval,'Coihueco',36);
    insert into COMUNA values(seq_comunaID.nextval,'niquen',36);
    insert into COMUNA values(seq_comunaID.nextval,'San Fabian',36);
    insert into COMUNA values(seq_comunaID.nextval,'San Nicolas',36);
    --O'HIGGINS
    insert into COMUNA values(seq_comunaID.nextval,'Rancagua',72);
    insert into COMUNA values(seq_comunaID.nextval,'Codegua',72);
    insert into COMUNA values(seq_comunaID.nextval,'Coinco',72);
    insert into COMUNA values(seq_comunaID.nextval,'Coltauco',72);
    insert into COMUNA values(seq_comunaID.nextval,'Donihue',72);
    insert into COMUNA values(seq_comunaID.nextval,'Graneros',72);
    insert into COMUNA values(seq_comunaID.nextval,'Las Cabras',72);
    insert into COMUNA values(seq_comunaID.nextval,'Machali',72);
    insert into COMUNA values(seq_comunaID.nextval,'Malloa',72);
    insert into COMUNA values(seq_comunaID.nextval,'Mostazal',72);
    insert into COMUNA values(seq_comunaID.nextval,'Olivar',72);
    insert into COMUNA values(seq_comunaID.nextval,'Peumo',72);
    insert into COMUNA values(seq_comunaID.nextval,'Pichidegua',72);
    insert into COMUNA values(seq_comunaID.nextval,'Quinta de Tilcoco',72);
    insert into COMUNA values(seq_comunaID.nextval,'Rengo',72);
    insert into COMUNA values(seq_comunaID.nextval,'Requinoa',72);
    insert into COMUNA values(seq_comunaID.nextval,'San Vicente Tagua Tagua',72);
    insert into COMUNA values(seq_comunaID.nextval,'Pichilemu',72);
    insert into COMUNA values(seq_comunaID.nextval,'Litueche',72);
    insert into COMUNA values(seq_comunaID.nextval,'Marchigue',72);
    insert into COMUNA values(seq_comunaID.nextval,'navidad',72);
    insert into COMUNA values(seq_comunaID.nextval,'Paredones',72);
    insert into COMUNA values(seq_comunaID.nextval,'San Fernando',72);
    insert into COMUNA values(seq_comunaID.nextval,'Chopica',72);
    insert into COMUNA values(seq_comunaID.nextval,'Chimbarongo',72);
    insert into COMUNA values(seq_comunaID.nextval,'Lolol',72);
    insert into COMUNA values(seq_comunaID.nextval,'Nancagua',72);
    insert into COMUNA values(seq_comunaID.nextval,'Palmilla',72);
    insert into COMUNA values(seq_comunaID.nextval,'Peralillo',72);
    insert into COMUNA values(seq_comunaID.nextval,'Placilla',72);
    insert into COMUNA values(seq_comunaID.nextval,'Pumanque',72);
    insert into COMUNA values(seq_comunaID.nextval,'Santa Cruz',72);
    --VALPARAISO
    insert into COMUNA values(seq_comunaID.nextval,'Isla de Pascua',48);
    insert into COMUNA values(seq_comunaID.nextval,'Los Andes',48);
    insert into COMUNA values(seq_comunaID.nextval,'Calle Larga',48);
    insert into COMUNA values(seq_comunaID.nextval,'Rinconada',48);
    insert into COMUNA values(seq_comunaID.nextval,'San Esteban',48);
    insert into COMUNA values(seq_comunaID.nextval,'Quilpue',48);
    insert into COMUNA values(seq_comunaID.nextval,'Limache',48);
    insert into COMUNA values(seq_comunaID.nextval,'Olmue',48);
    insert into COMUNA values(seq_comunaID.nextval,'Villa Alemana',48);
    insert into COMUNA values(seq_comunaID.nextval,'La Ligua',48);
    insert into COMUNA values(seq_comunaID.nextval,'Cabildo',48);
    insert into COMUNA values(seq_comunaID.nextval,'Papudo',48);
    insert into COMUNA values(seq_comunaID.nextval,'Petorca',48);
    insert into COMUNA values(seq_comunaID.nextval,'Zapallar',48);
    insert into COMUNA values(seq_comunaID.nextval,'Quillota',48);
    insert into COMUNA values(seq_comunaID.nextval,'Hijuelas',48);
    insert into COMUNA values(seq_comunaID.nextval,'La Calera',48);
    insert into COMUNA values(seq_comunaID.nextval,'La Cruz',48);
    insert into COMUNA values(seq_comunaID.nextval,'Nogales',48);
    insert into COMUNA values(seq_comunaID.nextval,'San Antonio',48);
    insert into COMUNA values(seq_comunaID.nextval,'Algarrobo',48);
    insert into COMUNA values(seq_comunaID.nextval,'Cartagena',48);
    insert into COMUNA values(seq_comunaID.nextval,'El Quisco',48);
    insert into COMUNA values(seq_comunaID.nextval,'El Tabo',48);
    insert into COMUNA values(seq_comunaID.nextval,'Santo Domingo',48);
    insert into COMUNA values(seq_comunaID.nextval,'San Felipe',48);
    insert into COMUNA values(seq_comunaID.nextval,'Catalemu',48);
    insert into COMUNA values(seq_comunaID.nextval,'Llay Llay',48);
    insert into COMUNA values(seq_comunaID.nextval,'Panquehue',48);
    insert into COMUNA values(seq_comunaID.nextval,'Putaendo',48);
    insert into COMUNA values(seq_comunaID.nextval,'Santa Maria',48);
    insert into COMUNA values(seq_comunaID.nextval,'Valparaiso',48);
    insert into COMUNA values(seq_comunaID.nextval,'Casablanca',48);
    insert into COMUNA values(seq_comunaID.nextval,'Concon',48);
    insert into COMUNA values(seq_comunaID.nextval,'Puchuncavi',48);
    insert into COMUNA values(seq_comunaID.nextval,'Quintero',48);
    insert into COMUNA values(seq_comunaID.nextval,'Vina del Mar',48);
    --BIO-BIO
    insert into COMUNA values(seq_comunaID.nextval,'Lebu',60);
    insert into COMUNA values(seq_comunaID.nextval,'Arauco',60);
    insert into COMUNA values(seq_comunaID.nextval,'Canete',60);
    insert into COMUNA values(seq_comunaID.nextval,'Contulmo',60);
    insert into COMUNA values(seq_comunaID.nextval,'Curanilahue',60);
    insert into COMUNA values(seq_comunaID.nextval,'Los Olamos',60);
    insert into COMUNA values(seq_comunaID.nextval,'Los Angeles',60);
    insert into COMUNA values(seq_comunaID.nextval,'Alto Bio Bio',60);
    insert into COMUNA values(seq_comunaID.nextval,'Antuco',60);
    insert into COMUNA values(seq_comunaID.nextval,'Cabrero',60);
    insert into COMUNA values(seq_comunaID.nextval,'Laja',60);
    insert into COMUNA values(seq_comunaID.nextval,'Mulchen',60);
    insert into COMUNA values(seq_comunaID.nextval,'Nacimiento',60);
    insert into COMUNA values(seq_comunaID.nextval,'Negrete',60);
    insert into COMUNA values(seq_comunaID.nextval,'Quilaco',60);
    insert into COMUNA values(seq_comunaID.nextval,'Quilleco',60);
    insert into COMUNA values(seq_comunaID.nextval,'San Rosendo',60);
    insert into COMUNA values(seq_comunaID.nextval,'Santa Barbara',60);
    insert into COMUNA values(seq_comunaID.nextval,'Tucapel',60);
    insert into COMUNA values(seq_comunaID.nextval,'Yumbel',60);
    insert into COMUNA values(seq_comunaID.nextval,'Concepcion',60);
    insert into COMUNA values(seq_comunaID.nextval,'Chiguayante',60);
    insert into COMUNA values(seq_comunaID.nextval,'Coronel',60);
    insert into COMUNA values(seq_comunaID.nextval,'Florida',60);
    insert into COMUNA values(seq_comunaID.nextval,'Hualpen',60);
    insert into COMUNA values(seq_comunaID.nextval,'Hualqui',60);
    insert into COMUNA values(seq_comunaID.nextval,'Lota',60);
    insert into COMUNA values(seq_comunaID.nextval,'Penco',60);
    insert into COMUNA values(seq_comunaID.nextval,'San Pedro de la Paz',60);
    insert into COMUNA values(seq_comunaID.nextval,'Santa Juana',60);
    insert into COMUNA values(seq_comunaID.nextval,'Talcahuano',60);
    insert into COMUNA values(seq_comunaID.nextval,'Tome',60);
    --ANTOFAGASTA
    insert into COMUNA values(seq_comunaID.nextval,'Antofagasta',24);
    insert into COMUNA values(seq_comunaID.nextval,'Mejillones',24);
    insert into COMUNA values(seq_comunaID.nextval,'Sierra Gorda',24);
    insert into COMUNA values(seq_comunaID.nextval,'Taltal',24);
    insert into COMUNA values(seq_comunaID.nextval,'Calama',24);
    insert into COMUNA values(seq_comunaID.nextval,'Allague',24);
    insert into COMUNA values(seq_comunaID.nextval,'San Pedro de Atacama',24);
    insert into COMUNA values(seq_comunaID.nextval,'Tocopilla',24);
    insert into COMUNA values(seq_comunaID.nextval,'Maria Elena',24);
    --METROPOLITANA
    insert into COMUNA values(seq_comunaID.nextval,'Colina',12);
    insert into COMUNA values(seq_comunaID.nextval,'Lampa',12);
    insert into COMUNA values(seq_comunaID.nextval,'Til Til',12);
    insert into COMUNA values(seq_comunaID.nextval,'Puente Alto',12);
    insert into COMUNA values(seq_comunaID.nextval,'Pirque',12);
    insert into COMUNA values(seq_comunaID.nextval,'San Jose de Maipo',12);
    insert into COMUNA values(seq_comunaID.nextval,'San Bernardo',12);
    insert into COMUNA values(seq_comunaID.nextval,'Buin',12);
    insert into COMUNA values(seq_comunaID.nextval,'Calera de Tango',12);
    insert into COMUNA values(seq_comunaID.nextval,'Paine',12);
    insert into COMUNA values(seq_comunaID.nextval,'Melipilla',12);
    insert into COMUNA values(seq_comunaID.nextval,'Alhue',12);
    insert into COMUNA values(seq_comunaID.nextval,'Curacavi',12);
    insert into COMUNA values(seq_comunaID.nextval,'Maria Pinto',12);
    insert into COMUNA values(seq_comunaID.nextval,'San Pedro',12);
    insert into COMUNA values(seq_comunaID.nextval,'Santiago',12);
    insert into COMUNA values(seq_comunaID.nextval,'Cerrillos',12);
    insert into COMUNA values(seq_comunaID.nextval,'Cerro Navia',12);
    insert into COMUNA values(seq_comunaID.nextval,'Conchali',12);
    insert into COMUNA values(seq_comunaID.nextval,'El Bosque',12);
    insert into COMUNA values(seq_comunaID.nextval,'Estacion Central',12);
    insert into COMUNA values(seq_comunaID.nextval,'Huechuraba',12);
    insert into COMUNA values(seq_comunaID.nextval,'Independencia',12);
    insert into COMUNA values(seq_comunaID.nextval,'La Cisterna',12);
    insert into COMUNA values(seq_comunaID.nextval,'La Florida',12);
    insert into COMUNA values(seq_comunaID.nextval,'La Granja',12);
    insert into COMUNA values(seq_comunaID.nextval,'La Pintana',12);
    insert into COMUNA values(seq_comunaID.nextval,'La Reina',12);
    insert into COMUNA values(seq_comunaID.nextval,'Las Condes',12);
    insert into COMUNA values(seq_comunaID.nextval,'Lo Barnechea',12);
    insert into COMUNA values(seq_comunaID.nextval,'Lo Espejo',12);
    insert into COMUNA values(seq_comunaID.nextval,'Lo Prado',12);
    insert into COMUNA values(seq_comunaID.nextval,'Macul',12);
    insert into COMUNA values(seq_comunaID.nextval,'Maipu',12);
    insert into COMUNA values(seq_comunaID.nextval,'nunoa',12);
    insert into COMUNA values(seq_comunaID.nextval,'Pedro Aguirre Cerda',12);
    insert into COMUNA values(seq_comunaID.nextval,'Penalolen',12);
    insert into COMUNA values(seq_comunaID.nextval,'Providencia',12);
    insert into COMUNA values(seq_comunaID.nextval,'Pudahuel',12);
    insert into COMUNA values(seq_comunaID.nextval,'Quilicura',12);
    insert into COMUNA values(seq_comunaID.nextval,'Quinta Normal',12);
    insert into COMUNA values(seq_comunaID.nextval,'Recoleta',12);
    insert into COMUNA values(seq_comunaID.nextval,'Renca',12);
    insert into COMUNA values(seq_comunaID.nextval,'San Joaquon',12);
    insert into COMUNA values(seq_comunaID.nextval,'San Miguel',12);
    insert into COMUNA values(seq_comunaID.nextval,'San Ramon',12);
    insert into COMUNA values(seq_comunaID.nextval,'Vitacura',12);
    insert into COMUNA values(seq_comunaID.nextval,'Talagante',12);
    insert into COMUNA values(seq_comunaID.nextval,'El Monte',12);
    insert into COMUNA values(seq_comunaID.nextval,'Isla de Maipo',12);
    insert into COMUNA values(seq_comunaID.nextval,'Padre Hurtado',12);
    insert into COMUNA values(seq_comunaID.nextval,'Penaflor',12);

--COLEGIOS


insert into COLEGIO values(seq_colegioID.nextval,'Teresa De Los Andes','Avenida Bulnes 1314',480);
insert into COLEGIO values(seq_colegioID.nextval,'Amanecer de Bulnes','Avenida Bulnes 0070',480);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela presidente Frei Montalva','Calle Senlub 8934',480);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Chillan','Martel Sandoval 0908',490);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Coyam','Los Pelches 1551',490);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Republica de Italia','Sep?lveda Bustos 435',490);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Particular Chillan Viejo','Longanizas 420',500);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Horeb','Chucrut 360',500);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio tecnologico Dario Salas','Avenida Alemana 7707',500);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Halcones del Carmen','Esmeralda 3338',510);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Virgen Del Carmen','Independencia 6758',510);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Mata Redonda','Araucaria 500',510);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Tomas Herrera Vega','el carmen 201',520);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Dafne Zapata','El carmen 101',520);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Cholguan','Yungay',520);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Puerta de la Cordillera','Calle Pintores 1212',530);
insert into COLEGIO values(seq_colegioID.nextval,'Francisco de Asis','Azir 7200',530);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Politecnico Jose Manuel Pinto','Carlos Pinto 1456',530);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Quillon','Educacion 0000',540);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Laguna Avendano','Sepulcro 324',540);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Amanda Chavez Navarrete','Acero 1297',540);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio San Ignacio','Av Los Batros 2350',550);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Politecnico Capitan Ignacio Pinto','David Gazmuri 451',550);
insert into COLEGIO values(seq_colegioID.nextval,'Licep polivalente Matia Ward','Av Los Carrera 199',550);
insert into COLEGIO values(seq_colegioID.nextval,'Divina Pastora','Ignacio Carrera Pinto 4141',560);
insert into COLEGIO values(seq_colegioID.nextval,'Nueva Esperanza','Colchauta 288',560);
insert into COLEGIO values(seq_colegioID.nextval,'Rayo de Luna','Colchauta 395',560);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio San Agustin','Ruta Los Conquistadores 170',570);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Grumete Cortez','Ruta Los Conquistadores 457',570);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Nueva America','Ruta Los Conquistadores 869',570);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Reino de Suecia','Av Independencia 300',580);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela F-55 Buchupureo','Calle Cobre 7589',580);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela B?sica Tauco','Av independencia 476',580);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Villa Jesus De Coelemu','Av independencia 0067',590);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Caravanchel','Av Libertador Bernardo O.Higgins 2000',590);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Domingo Ortiz de Rozas','Calle Los Bronzes 570',590);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Arturo Prat Chacon','Alcalde Campos Carvajal 040',600);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Gloria Navales','Alcalde Campos Carvajal 050',600);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Adventista Quirao','Florida 10',600);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Nuestra Senora Del Carmen','Carmen Gloria 0770',610);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Nibaldo Sepulveda Fernandez','Matias Sepulveda Calvo 5050',610);
insert into COLEGIO values(seq_colegioID.nextval,'ESCUELA BASICA HUACALEMU','Av Hualaihue km 4',610);
insert into COLEGIO values(seq_colegioID.nextval,'Complejo Educacional Valle Del Itata','Puente Amarillo 0510',620);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela San Ignacio de Palomares','Puente Amarillo 5010',620);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Virginio Arias','Puente Amparillo 1050',620);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Polivalente Republica del Paraguay','Ruta 126 896',630);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Santa Teresita Coelemu','El camino Roble Cector Chorrillo Huechuraba',630);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Villa Jesus De Coelemu','Heroes de la Concepcion 340',630);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio San Jose','El Canelo 1037',640);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Concepcion de San Carlos','Malaga 951',640);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Sagrado Corazon De Jesus','Ernesto Riquelme 08',640);
insert into COLEGIO values(seq_colegioID.nextval,'colegio cumbres de coihueco','N-505 1807',650);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Lorenzo Mondanelli','Av Coihueco 0754',650);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio San Agustin de Chillan','Camino Coihueco Km 6',650);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Polivalente San Gregorio','Los Abedules 050',660);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela San Jorge De Niquen','Los robles 1777',660);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio El Arbol de la Vida','El Avellano 1040',660);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Basica Fabian de la Fuente','Los Charcos 1260',670);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Polivalente Jorge Alessandri de San F.','Cachapoal 0700',670);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Basica Trabuncura','Llovizna 5004',670);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio bicentenario San Nicolas','Calle Arturo Prat 202',680);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Bicentenario de Excelencia Polivalente de San Nicolas','Balmaceda 462',680);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Sergio Martin Alamos','Balmaceda 876',680);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Eduardo de Geyter','Italia 582',900);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Aurora de Chile','Mac Iver',900);
insert into COLEGIO values(seq_colegioID.nextval,'COLEGIO MANZANAL','Claudio Matte 635',900);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Jesus Andino de Codegua','Almirante Thrawn 450',910);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Natalia Peralta de Codegua','Safiro 458',910);
insert into COLEGIO values(seq_colegioID.nextval,'Instituto Lautaro De Codegua','Naturaleza 240',910);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Cerrillos','Av. Cachapoal S/N',920);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Alberto Hurtado','Subteniente Valenzuela S/N',920);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Claudio Arrau Leon Donihue','Donihue S/N',920);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Agricola San Vicente De Paul','Los Historiadores 200',930);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Politecnico Berta Zamorano Lizana','Los Historiadores 450',930);
insert into COLEGIO values(seq_colegioID.nextval,'Instituto Monsenor Lecaros','Av libertadores 5070',930);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Claudio Arrau Leon Donihue','Av Libertadores 3004',940);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Alberto Hurtado','Subteniente Valenzuela',940);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Cerrillos','Av. Cachapoal S/N',940);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Graneros','Calle Jose M Cousino 141',950);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Maria Escobillana','Los Alerces',950);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Hernan Olguin Maibe?','El Olimpo 777',950);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Mistral','Francisco A Encina',960);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio San Carlos','Sta. Adriana Ote. 805',960);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Municipal Romilio Arellano Troncoso','John Kennedy',960);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio San Ignacio','Miguel Ramirez 216',970);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Nahuelcura','Av San Juan 378',970);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Diego Portales','Los Portales S/N',970);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Alcides Reyes Frias','La Gloria 53',980);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela De Panquehue Malloa','Los Manqueques 8000',980);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Vicente Huidobro','Rengo 4570',980);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Andres Bello','Independencia 278',990);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio La Mision','Luco 423b',990);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Nuestra Esperanza','Heraldos 350',990);
insert into COLEGIO values(seq_colegioID.nextval,'Olivar College','Aparta 7666',1000);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Maria Villalobos Arteaga','Av Manuel Rodriguez 200',1000);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio GULTRO','Los Sabuesos 1221',1000);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Cryptocarya Alba','Hernan Gajardo 5',1010);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Alcalde Pedro Urbina','Walker Martenez 319',1010);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Jean Buchannan De Larrain','Manuel Ossa',1010);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Elena Gaete Darbeaux',' El Trueno 1026',1020);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Latinoamericano','Independencia 840',1020);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Jose Bernales Castillo','El trueno 480',1020);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Sagrado Corazon de Jesus','Las Moras 1345',1030);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio La Vina','Los Arandanos 5434',1030);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Republica De Italia','Jaime Barrientos Soto 303',1030);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Antilon Rengo','Arturo Prat 856',1040);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio La Paz','Arturo Prat 349',1040);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Alma Mater','Arturo Prat 198',1040);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Tricahue','Lss Fresas 670',1050);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Requinoa','Las Bayas 156',1050);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Canada','Santa Licila 125',1050);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio El Salvador','Horacio Aranguiz 1500',1060);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Nehuen','German Riesco 1662',1060);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Espana','Av. Espa?a 115',1060);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Preciosa Sangre Pichulemu','Las Orcas 5470',1070);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Charlys School','Jose Joaquin P?rez 361',1070);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Libertadores','Millaco 750',1070);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Cardenal Rail Silva Henriquez','Camino a Alcones',1090);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo El Rosario','Central Rapel',1090);
insert into COLEGIO values(seq_colegioID.nextval,'Instituto Cardenal Caro','Alforjas',1100);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela America','Las Culebras 1800',1100);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Confederacion Helvetica','Las mantas 1456',1110);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Los Mayos','Las frasadas 8756',1110);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Municipal Pablo Neruda','Los versos S/N',1110);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Mirella Catalan','Los Paredones S/N',1120);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela De Lenguaje Newen','San joaquin',1120);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Mercedes Urzua Diaz','Nueva Esperanza S/N',1120);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Marista San Fernando','Marcelino Champagnat 0180',1130);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Los Arrayanes','Campanario 1256',1130);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio villa Centinela','Reposo 456',1130);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Libertador OHiggins','Constelacion 700',1140);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Ferman Del Real Castillo','Los Soldados 1566',1140);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Alerce','Pisagua 473',1150);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Alto Miraflores','Calle Miraflores',1150);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio San Nicolas','Calle Miraflores',1150);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Lolol','Gral. Bernardo OHigginsdire',1160);
insert into COLEGIO values(seq_colegioID.nextval,'Nancagua school','21 De Mayo 405',1170);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Lomas Blancas','Grandes Generales S/N',1170);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio El Principito','Los Tarros 1205',1170);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Municipal De Palmilla','Elena Errazuris 145',1180);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Valle hermoso','Avenida central km 14',1180);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo San Jose del Carmen','Avenida Central km 3',1180);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio de Lenguaje Padre Pio','Manuel Rodriguez',1190);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Violeta Parra Sandoval','Hakuna Matata 1214',1190);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Bicentenario Victor Jara','Av Vicentenario 214',1190);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo San Francisco','Miraflores 847',1200);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela La Tuna i Sector la Tuna','Los At?nes 747',1200);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Pumanque','Pje Pumanque 140',1210);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Colhue','Los pumas 4567',1210);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Manquemavida','Barreales 771',1220);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Santa Cruz','Av Daniel Barros Grez 86',1220);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Santa Cruz de Unco','Adriano Diaz 500',1220);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Lorenzo Baeza Vega','Isla de Pascua',1230);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Catolico Hermano Eugenio Eyraud','Isla de Pascua',1230);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Mario Luigi','Isla de Pascua',1230);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Internacional Valparaiso S.P.A','Av. Alemania 4875',1240);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Salesiano Valparaiso','Don Bosco 88',1240);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Maria Auxiliadora, Valparaiso','Av. Quebrada Verde 195',1240);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela San Jose','Calle Larga 2103',1250);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Tecnico Profesional Pedro Aguirre Cerda',' 1950',1250);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Pedro Aguirre Cerda','Calle Larga 1245',1250);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Parroquial','Autopista Los Libertadores 975',1260);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Manuel Leon Salinas','La Rinconada',1260);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Perfecto De La Fuente Del Villar','E-841',1260);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Pablo Neruda','Av. Alessandri 800',1270);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Municipal','Poblacion San Esteban 1313',1270);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Silvio Zenteno Vergara','Guillerma Wyvern 1242',1270);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Nahuen de Quilpue','Bruselas 550',1280);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Fundadores de Quilpue','Alcalde Subercaseaux 1530',1280);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Coeducacional Particular Quilpue','Av. Los Carrera 981',1280);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela N 49 Colegio Italiano Limache','12 de Febrero 173',1290);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Waldorf San Fco. de Limache',' Riquelme 11',1290);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Nacional de Limache','Av. Jose Tomas Urmeneta 473',1290);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo De Olmue','Av. Arturo Prat 4917',1300);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Ignacio Carrera Pinto Olmue','Av. Arturo Prat 4531',1300);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Atenas','101, Av. Arturo Prat',1300);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Internado Aleman',' Arrieta 460',1310);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Educrece Villa Alemana','Sexta 100-198',1310);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio San Antonio','Caupolican 491',1310);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio San Carlos','Ortiz de Rosas 909',1320);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Republica de Venezuela','Diego Portales 394',1320);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Gabriela Mistral','Serrano 51',1320);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Andres Bello','Errazuriz 295',1330);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Particular Pehuen','Pje. Gabriela Mistral 212',1330);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Bicentenario','Humeres 1800',1330);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Antonio Zanoletti','Serrano 750',1340);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Tecnico Profesional Papudo','Chorrillos 191',1340);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Catolico Presidente Manuel Montt','Silva 615',1350);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Jose Manuel Borgo?o N??ez',' Cuartel 145',1350);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Sagrado Corazon Chincolco','Pedro Montt S/N',1350);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Zapallar','German Riesco 209',1360);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Parroquial Francisco Didier','Zapallo 431',1360);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Balneario de Cachagua','Sopaipillas S/N',1360);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Valle de Quillota','Merced 99',1370);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Cristiano De Quillota','Jose Miguel Carrera 550',1370);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Marista Quillota - Diego Echeverria','Diego Echeverr?a 701',1370);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Basica Benjamin Matte Larrain','Hijole 3012',1380);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Manica Hurtado Edwards','Petorquita 621',1380);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio San Nicolas','Petorquita 1455',1380);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela B?sica El Libertador','Calama 1560-1576',1390);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Palestina','Alonso de Ercilla 50',1390);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Especial Armonia','Freire 972',1390);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Salvatierra','Av. Sta. Cruz 5101',1400);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Maria Alonso Chacon','Av. Sta. Cruz 832',1400);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Tecnico Agricola Obispo Rafael Lira Infante','Av. Sta. Cruz 51',1400);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Christa Mock','Panamericana Norte 1543',1410);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Ulda Aracena','Pedro E Godoy S/N',1410);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Juan Rusque','Pedro Felix Vicuna 646',1410);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Particular Sara Cruchaga','Gregorio Mira 189',1420);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Espiritu Santo San Antonio','Los Aromos 1351',1420);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Padre Andre Coindre','Felix Vergara 770',1420);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Teresa de Los Andes Algarrobo',' El Molle',1430);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Carlos Alessandri Altamirano','El Olmo 1599',1430);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Nuestro Tiempo Algarrobo','El Espino 2337',1430);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Peumayen','Avda. Cartagena 745',1440);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Presidente Aguirre Cerda','Avda. Cartagena 998',1440);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Villa Cartago','Avenida Cartago Poniente 398',1440);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio El Quisco','Del Centauro N? 60',1450);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio San Miguel Arc?ngel','Av Francia 0621',1450);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio El alba El Quisco','Lobos Tranquilos 020',1450);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio El Tabo','Av Afganistan 4567',1460);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Santo Domingo De Guzman',' Necochea 276',1470);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Santa Ana','Sto Domingo 104',1470);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Maria Auxiliadora','Av. Quebrada Verde 195',1470);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo San Felipe','Jose de Rojas',1480);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Alonso de Ercilla Prat','Arturo Prat 337',1480);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Internacional Valparaiso S.P.A.',' Av. Alemania 4875',1490);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Salesiano Valpara?so','Don Bosco 88',1490);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Politecnico De Llay Llay','Covadonga 142',1500);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Agustin Edwards','Agustin Edwards 546',1500);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Salvador Gonzalez','Las Lomas 395',1500);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Vespertino Panquehue','Ruta 60 80',1510);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Independencia','Francisco Bulnes',1510);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Marie Poussepin','Comercio 100',1520);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Manuel Marin Fritis','Batalla de Chacabuco',1520);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Cervantino','Ruta Cervatana 756',1520);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Santa Maria College','Lautaro 54',1530);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Santa Maria de Aconcagua','Lautaro 12',1530);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Dario Salas','Calle Jahuel 729',1530);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio San Pedro Nolasco','Victoria 2762',1540);
insert into COLEGIO values(seq_colegioID.nextval,'Ex Colegio Aleman Valparaiso','Concepcion 499',1540);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Agustin Edwards Valparaiso','Carrera 636',1540);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Leonardo Da Vinci Casablanca',' Alejandro Galaz 989',1550);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Santa Barbara de la Reina','Av Arturo Prat 247',1550);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Arrayan','Del Roble 498',1550);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Altazor Concon','Calle 5 650',1560);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Villa Aconcagua','Rio Limari 335',1560);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Internacional SEK Pacifico','San Estanislao 50',1560);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio General Jose Velasquez','Pje Pablo Neruda 12',1580);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Campiche','Pje Pablo Neruda 1200',1580);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela La Greda','Pje Pablo Neruda 0212',1580);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Don Orione','Luis Orione 721',1590);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Ingles Quintero','Alonso de Quintero 475',1590);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Santa Filomena','Francia 1442',1590);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Momtesorri Vi?na Del Mar','Oriente 216',1600);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Ruben Castro','Castracion 345',1600);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela UNESCO Vina del Mar','Calle Escuela 1',1600);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Bicentenario Isidora Ramos','Luis Cruz Martinez #93',1610);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela La Fortuna','Pasaje Lebu 4769',1610);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Arauco','Los Boldos 001',1620);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio El Bosque',' Prat 183',1620);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo San Francisco De Asis','Carlos Condell 520',1620);
insert into COLEGIO values(seq_colegioID.nextval,'Instituto San Jos?','Av Canete 780',1630);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio La Granja','Psje Record 60',1630);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Politecnico Canete','Esmeralda 960',1630);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela San Luis','Gran Calle Contulmo km 10',1640);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Polivalente Nahuelbuta','Gran Calle Contulmo km 1',1640);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Particular Huhillinco Alto','Gran Calle Contulmo km 35',1640);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Continental','Juan Gomez 145',1650);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela D-758 Ramiro Roa','Maratin 450',1650);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Pablo Neruda','Arturo Perez Canto 123',1650);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Gaspar Cabrales','Los Alamos S/N',1660);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Felix Eyheramendy','Pedro Eyheramendy N? 579',1660);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Cristo Redentor','P-46 701',1660);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Los angeles','Ercilla 389',1680);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Santo Tomas Los Angeles','Bernardo OHiggins 756',1680);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Proacap','Almagro 847',1680);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela G-1181 Ralco Lepoy','Alto bio bio mk 12',1690);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Particular Quepuca-Ralco','Alto Bio Bio km 10',1690);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Altazor','Baltazar 1773',1700);
insert into COLEGIO values(seq_colegioID.nextval,'liceo Basico Dr. Victor Rios Ruiz','Ramones 145',1700);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Peumayen','Ludwig van Beethoven 32',1710);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio San Jose','Membrillar 300',1710);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Manuel Za?artu Zanartu','Calle las Violetas 569,',1710);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Polivalente H. Maestra de la Santa Cruz','P. Felix Eicher',1720);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Borderio','Avenida Matta 150',1730);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio San Bernardino De Sena','Calle Mision 265',1730);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Villa La Granja','Faro de Luz 120',1730);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio San Juan de Dios','Santa Feria 679',1740);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Teresiano Padre Enrique','Av. Espana 1125',1740);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Nacimiento de Nuestro Senor','Villa Alegre 1415',1740);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Agricola De Negrete','Parcela 1 y 2 sector espiga de oro Negrete',1750);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo polivalente la frontera','Emilio Serrano 30',1750);
insert into COLEGIO values(seq_colegioID.nextval,'Esc. Toqui Lautaro','Nacimiento',1750);
insert into COLEGIO values(seq_colegioID.nextval,'Instituto Valle de Sol','Av. Arturo Prat 1491',1760);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Santa Barbara','Rosas 365',1760);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Agricola Los Mayos','Santa Barbara 1314',1760);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Francisco Bascunan Guerrero','Arturo Prat 398',1770);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Isidora Aguirre Tupper','Exequiel Vallejos 550',1780);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio San Jorge','Los Canelos',1780);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Santa Barbara','Rosas 365',1790);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Enrique Bernstein Carabantes','Diego Portales 155',1790);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Cacique Levin','Los Opresores 0000',1790);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela E-1013, Tucapel','Avenida Restico Molina N?240',1800);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Andres Alcazar Tucapel','Los rios 765',1800);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio San Diego De Alcali','Los Valles 7778',1800);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Raiquen','Hernan Gajardo 5',1810);
insert into COLEGIO values(seq_colegioID.nextval,'Instituto San Sebastian de Yumbel (E.Media)','Quintana S/N',1810);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Luis Alberto Saldes Irarrazabal','Quezada 750',1810);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Creaci?n de Concepcion','Arturo Perez Canto 902',1820);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Inmaculada Concepcion','Anibal Pinto 2453',1820);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio San Joaquin','Central 17',1820);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Pinares','Camino a Chiguayante 5583',1830);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Andres Bello','Pinares 503',1830);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Particular Aurora de Chile','Avenida Manuel Rodriguez 604',1830);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Particular Gabriela Mistral','Buen Retiro 790',1840);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Particular San Pedro','Lautaro 431',1840);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Amanecer','Paso Seco 2000',1840);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Luis de Alava','Calle Carlos Condell 701',1850);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Ines Enriquez Frodden','Ruta N-48-O 759',1850);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio SSCC','Av. Cristobal Col?n 8865',1860);
insert into COLEGIO values(seq_colegioID.nextval,'High Scope','Av. Cristobal Col?n 8876',1860);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Particular Manuel Rodriguez','Avenida Los Copihues 390',1860);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Valle de Hualqui','Fresia 196',1870);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Nueva Republica','Pasaje Onas 451',1870);
insert into COLEGIO values(seq_colegioID.nextval,'Christian College Hualqui','Ramon Freire 689',1870);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Bicentenario Padre Manuel d.Alzon-Lota','Julio Lobos 101',1880);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Thompson Matthews','Juan Manuel Valle 430',1880);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Adventista, Lota Alto','Carlos Cousino 154',1880);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio "El Refugio"','O.Higgins 115',1890);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio A-Lafken','Heriberto Urz?a 127',1890);
insert into COLEGIO values(seq_colegioID.nextval,'Complejo Educacional Gloria Mendez Briones','Roberto Ovalle 99',1890);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Amanecer San Carlos','Av. Portal de San Pedro 7370',1900);
insert into COLEGIO values(seq_colegioID.nextval,'Saint Joan College','Jeanne D.Arc 350',1910);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Jahve Nisi','Nigerundayo 1197',1910);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Madre Dominicas de Santa Juana','Huallerehue',1910);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Etchegoyen - Talcahuano','Anibal Pinto 332',1920);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Arturo Prat','Michimalonco 2555',1920);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Espiritu Santo','Avenida Desiderio Garcia 519',1920);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Guillermo Velasco','Anibal Pinto 1140',1930);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Republica de Ecuador','Anibal Pinto 1210',1930);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Margarita Naseau','Riquelme 1211',1930);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Antofagasta','Ascoten Sur 220',1940);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Universitario Antonio Rendic','Av. Universidad de Antofagasta 02700',1940);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Chacares','Av. Cerro Paranal 501',1940);
insert into COLEGIO values(seq_colegioID.nextval,'Complejo Educativo Juan Jose Latorre','Av. Serrano 1000',1950);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Maria Angelica Elizondo Bricero','Av. Almte. Latorre 898',1950);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Julia Herrera Varas','Moluscos 140',1950);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Caracoles G-101','Eduardo Frei km 7',1960);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Humanista "Victor Hugo Carvajal Meza"','Esmeralda 596',1970);
insert into COLEGIO values(seq_colegioID.nextval,'escuela alondra','Av Arturo Prat 1849',1970);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Alondra Rojas','Eduardo Frei km 38',1970);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Calama','Brasil 3597',1980);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Adventista Calama','Eduardo Abaroa 1490',1980);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Chuquicamata','Los Mineros 14',1980);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Santo Tomas','Arturo Prat 837',1990);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Femenino Madre del Rosario','Av. Bonilla 8945',1990);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio San Agustin de Antofagasta','Los Pimientos 7,',1990);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela E-26','Ignacio Carrera Pinto 499',2000);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Pablo Neruda','Pje. Sucre 2274',2010);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Bernardo O.Higgins E-10','Av. 18 de Septiembre 2732-2914',2010);
insert into COLEGIO values(seq_colegioID.nextval,'Politecnico Tocopilla','Ruta 1 1183',2010);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela D-133 Arturo Perez Canto','S.N. Calle Gabriela Mistral',2020);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo T?cnico Profesional - Cientifico Humanista','Av. Pedro de Valdivia',2020);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela G-15 Ignacio Carrera Pinto','Los Presidentes 140',2020);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio San Antonio de Colina','Santo Domingo 2314',2030);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Santa Cruz de Chicureo','Av. chicureo 860',2030);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio particular Divina Maria','Capuchinos 635',2030);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio San Jose de Lampa','Miguel Angel 180',2040);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Emprender Larapinta','Los Halcones 1000',2040);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Alborada de Lampa','Isabel Riquelme 811',2040);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Particular La Merced','Av. Barros Arana 698',2050);
insert into COLEGIO values(seq_colegioID.nextval,'San Pao de Pietrelcina de Tiltil','Arturo Prat 701-721',2050);
insert into COLEGIO values(seq_colegioID.nextval,'INTERNADO MANUEL RODRIGUEZ DE TIL TIL','Av. Barros Arana 594',2050);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Araucarias Cordillera Ltda Sede Basica','German Ebbinghauss 2944',2060);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Nueva Creacion, Puente Alto','Estadio 140',2060);
insert into COLEGIO values(seq_colegioID.nextval,'Centro Educacional San Fernando de Puente Alto','Av Luis miguel 180',2060);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Almenar de Pirque','Hernan Prieto 724',2070);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Colonial de Pirque',' Av. Concha Y Toro s/n, parcela 44',2070);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Virginia Subercaseaux','Av. Virginia Subercaseaux 2800',2070);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Polivalente San Jose de Maipo','amino Al Volcan 19845',2080);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Andino Antuquelen','Los Olmos 10988',2080);
insert into COLEGIO values(seq_colegioID.nextval,'colegio san jose school',' Sta Petronila 3',2080);
insert into COLEGIO values(seq_colegioID.nextval,'Instituto Sagrado Corazon de San Bernardo','Arturo Prat 881',2090);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio American Academy','Barros Arana 651',2090);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Superior del Maipo','Arturo Dagnino 131',2090);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Buin','Calle 1 1020',2100);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Pukaray','Kennedy 929-939',2100);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio San Marcel','La Marcha 1616',2100);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Rieljan College','Av. Calera de Tango 6',2110);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio San Bartolome de Calera De Tango','El Trebolar 1',2110);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Poetisa Gabriela Mistral','Caleteras 275',2110);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Santa Maria de Paine','Av. Gral. Baquedano 348',2120);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Moderno Paine','Alegre 15',2120);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio San Gennaro','Alegre 281',2120);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio San Sebastian de Melipilla','Wolfgang Amadeus Mozart 131',2130);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Particular Melipilla','Vicuna Mackenna 0900',2130);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Alonso de Ercilla',' Libertad 1150',2130);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Antu','Trinidad Ramirez 0750',2140);
insert into COLEGIO values(seq_colegioID.nextval,'Eco Escuela San Alfonso','Gran Avenida 213',2140);
insert into COLEGIO values(seq_colegioID.nextval,'Instituto San Luis de Curacavi','Las Rosas 264',2150);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio North Cross Curacavi','Presbitero Moraga Sur 150',2150);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo de Curacavi Presidente Balmaceda','Covadonga 451',2150);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Nuestra Sra. de la Guardia','Maria pinto S/N parcela 12',2160);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Polivalente','Francisco Donoso 310-250',2160);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Santa Emilia','Calle los Aromos',2160);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Municipal de San Pedro','Cromas 145',2170);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Enrique Reymond','La esmeralda 143',2170);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela de Lo Encanado','Calle Las Tormentas 1534',2170);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Santa Cruz','Nataniel Cox 1349',2180);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Metodista de Santiago','Arturo Prat 1655',2180);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio San Antonio','Santo Domingo 2314',2180);
insert into COLEGIO values(seq_colegioID.nextval,'Escuela Don Orione','Av. Pedro Aguirre Cerda 7335',2190);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Particular Mater Dei','Lo Errazuriz 186',2190);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio San Jose de Cerrillos','Mujica 335',2190);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Enrique Alvear de Cerro Navia','Resbalon 1685',2200);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio San Damian de Molokai','Estados Unidos 1364',2200);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio San Vicente Ferrer','Prof Dario Salazar 1803',2200);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Cristobal Colon','Berna,',2210);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio San Diego S.A','Diego Silva Henriquez 1791',2210);
insert into COLEGIO values(seq_colegioID.nextval,'Mary Anne School','Av. Independencia 4994',2210);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Particular Tantauco El Bosque','Gral Manuel Tovarias 385',2220);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Santo Tomas','Gran Avenida Jose Miguel Carrera 13231',2220);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Polivalente Agustiniano','Av. Central 555,',2220);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Estacion Central','Purisima 58',2230);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Echaurren','Luis Infante Cerda 5484',2230);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Hernando de Magallanes','La Portada 5635',2230);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Pumahue Huechuraba','Av. Sta. Rosa de Huechuraba 7201',2240);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Saint Joseph School de Huechuraba','Avenue El Guanaco 1270',2240);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Santa Teresa de Jesus de los Andes','Av. Recoleta 6187',2240);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Santa Maria de Cervellon','Av. Independencia 1783',2250);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Jean Jacques','Av. Independencia 2713',2250);
insert into COLEGIO values(seq_colegioID.nextval,'COLEGIO GEORGE WASHINGTON',' Echeverria 935',2250);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Santa Maria de Los Angeles','Gran Av Jose Miguel Carrera 9439',2260);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Palestino La Cisterna','Av. el Parron 554',2260);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Portal de La Cisterna','Esmeralda 6305',2260);
insert into COLEGIO values(seq_colegioID.nextval,'Soc Educacional Santa Maria de la Florida','Avenida Vicuna Mackenna Poniente 6185',2270);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Chillan','Av. Vicuna Mackenna Ote. 11462',2270);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Raices Altazor','El Hualle Sur 8605',2270);
insert into COLEGIO values(seq_colegioID.nextval,'Liceo Malaquias Concha','Quilpue 7852',2280);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio San Marcelo, La Granja','Baquedano 095',2280);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Municipal Proceres de Chile','Linares 875',2280);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Polivalente Almendral de La Pintana','La Primavera 2906',2290);
insert into COLEGIO values(seq_colegioID.nextval,'Chilean Eagles College La Pintana','Venancia Leiva 1741',2290);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Cardenal Jose Maria Caro','San Leandro 0369',2290);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Santa Maria Reina','Av. Alcalde Fernando Castillo Velasco 7437',2300);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio Larrain','Av. Larrain 6227',2300);
insert into COLEGIO values(seq_colegioID.nextval,'Colegio la Abadia','Valenzuela Puelma 8361',2300);


-- Plan De Viaje

insert into PLAN_VIAJE values(seq_planViajeID.nextval,'Plan Pucon','desc');
insert into PLAN_VIAJE values(seq_planViajeID.nextval,'Plan Villarica','descripcion');
insert into PLAN_VIAJE values(seq_planViajeID.nextval,'Plan Rio de Janeiro','descripcion');
insert into PLAN_VIAJE values(seq_planViajeID.nextval,'Plan Bariloche','desc');
insert into PLAN_VIAJE values(seq_planViajeID.nextval,'Plan Machu Picchu','desc');
insert into PLAN_VIAJE values(seq_planViajeID.nextval,'Plan Sao Paulo','desc');

--USUARIO
insert into USUARIO values('11111111-k','ChupetesuazoCampeon@gmail.com','chirimoyas','Roberto','Lopez');
--DUEnO
insert into DUEÑO values('11111111-k');
insert into EJECUTIVO_VENTA values('11111111-k');
insert into APODERADO values('11111111-k');
insert into REPRESENTANTE values('11111111-k');

insert into USUARIO values('22222222-k','nc@gmail.com','choco','Nicolas','Carvajal');
insert into EJECUTIVO_VENTA values('22222222-k');


--USUARIO
INSERT INTO USUARIO VALUES('20454125-4','almezat@gmail.com',1235,'Miguel','Herrera');
INSERT INTO USUARIO VALUES('22321123-9','gwaineat1@gmail.com',1235,'Anais','Perez');
INSERT INTO USUARIO VALUES('21678925-k','fil_anore_03@gmail.com',1235,'Fileanore','Garcia');
INSERT INTO USUARIO VALUES('21334123-7','emi_huer@gmail.com',1235,'Emilio','Huerta');

--REPRESENTANTE
INSERT INTO REPRESENTANTE VALUES('20454125-4');
INSERT INTO REPRESENTANTE VALUES('22321123-9');
INSERT INTO REPRESENTANTE VALUES('21678925-k');
INSERT INTO REPRESENTANTE VALUES('21334123-7');

--CURSO
INSERT INTO CURSO VALUES(1,'8°BF','21334123-7',1404);
INSERT INTO CURSO VALUES(2,'2°MA','20454125-4',2688);
INSERT INTO CURSO VALUES(3,'1°MC','22321123-9',882);
INSERT INTO CURSO VALUES(4,'1°MB','21678925-k',882);

--CONTRATO
INSERT INTO CONTRATO VALUES(1,1,1500000,SYSDATE,'13/11/2020','TEXTO AQUÍ',1);
INSERT INTO CONTRATO VALUES(2,2,2000000,SYSDATE,'21/12/2020','TEXTO AQUÍ',2);
INSERT INTO CONTRATO VALUES(3,3,3000000,SYSDATE,'31/12/2020','TEXTO AQUÍ',5);
INSERT INTO CONTRATO VALUES(4,4,5000000,SYSDATE,'14/12/2020','TEXTO AQUÍ',6);

commit;
